//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuCoinApp.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KuCoinApp.Localization.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KuCoin Accounts.
        /// </summary>
        internal static string AccountsTitle {
            get {
                return ResourceManager.GetString("AccountsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        internal static string APIKey {
            get {
                return ResourceManager.GetString("APIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Passphrase.
        /// </summary>
        internal static string APIPassphrase {
            get {
                return ResourceManager.GetString("APIPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Secret.
        /// </summary>
        internal static string APISecret {
            get {
                return ResourceManager.GetString("APISecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency.
        /// </summary>
        internal static string BaseCurrency {
            get {
                return ResourceManager.GetString("BaseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow.
        /// </summary>
        internal static string Borrow {
            get {
                return ResourceManager.GetString("Borrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candle.
        /// </summary>
        internal static string Candle {
            get {
                return ResourceManager.GetString("Candle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candles.
        /// </summary>
        internal static string Candles {
            get {
                return ResourceManager.GetString("Candles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Price.
        /// </summary>
        internal static string ClosePrice {
            get {
                return ResourceManager.GetString("ClosePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        internal static string Credentials {
            get {
                return ResourceManager.GetString("Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit API Credentials.
        /// </summary>
        internal static string CredentialsTitle {
            get {
                return ResourceManager.GetString("CredentialsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Credentials.
        /// </summary>
        internal static string EditCredentials {
            get {
                return ResourceManager.GetString("EditCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Futures.
        /// </summary>
        internal static string EditFutures {
            get {
                return ResourceManager.GetString("EditFutures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to the internet..
        /// </summary>
        internal static string ErrorNoInternet {
            get {
                return ResourceManager.GetString("ErrorNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Futures.
        /// </summary>
        internal static string Futures {
            get {
                return ResourceManager.GetString("Futures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Futures API Credentials.
        /// </summary>
        internal static string FuturesCredentialsTitle {
            get {
                return ResourceManager.GetString("FuturesCredentialsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holds.
        /// </summary>
        internal static string Holds {
            get {
                return ResourceManager.GetString("Holds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K-Line.
        /// </summary>
        internal static string K_Line {
            get {
                return ResourceManager.GetString("K-Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K-Lines.
        /// </summary>
        internal static string K_Lines {
            get {
                return ResourceManager.GetString("K-Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lend.
        /// </summary>
        internal static string Lend {
            get {
                return ResourceManager.GetString("Lend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leverage.
        /// </summary>
        internal static string Leverage {
            get {
                return ResourceManager.GetString("Leverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leveraged.
        /// </summary>
        internal static string Leveraged {
            get {
                return ResourceManager.GetString("Leveraged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        internal static string Limit {
            get {
                return ResourceManager.GetString("Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Loss.
        /// </summary>
        internal static string LimitLoss {
            get {
                return ResourceManager.GetString("LimitLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Order.
        /// </summary>
        internal static string LimitOrder {
            get {
                return ResourceManager.GetString("LimitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Price.
        /// </summary>
        internal static string LimitPrice {
            get {
                return ResourceManager.GetString("LimitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquidated.
        /// </summary>
        internal static string Liquidated {
            get {
                return ResourceManager.GetString("Liquidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquidation Price.
        /// </summary>
        internal static string LiquidationPrice {
            get {
                return ResourceManager.GetString("LiquidationPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquidation Warning.
        /// </summary>
        internal static string LiquidationWarning {
            get {
                return ResourceManager.GetString("LiquidationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KuCoin App.
        /// </summary>
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        internal static string Margin {
            get {
                return ResourceManager.GetString("Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin Order.
        /// </summary>
        internal static string MarginOrder {
            get {
                return ResourceManager.GetString("MarginOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        internal static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Order.
        /// </summary>
        internal static string MarketOrder {
            get {
                return ResourceManager.GetString("MarketOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Amount.
        /// </summary>
        internal static string QuoteAmount {
            get {
                return ResourceManager.GetString("QuoteAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Currency.
        /// </summary>
        internal static string QuoteCurrency {
            get {
                return ResourceManager.GetString("QuoteCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh K-Line.
        /// </summary>
        internal static string RefreshChart {
            get {
                return ResourceManager.GetString("RefreshChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Symbols.
        /// </summary>
        internal static string RefreshSymbols {
            get {
                return ResourceManager.GetString("RefreshSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandbox Mode.
        /// </summary>
        internal static string SandboxMode {
            get {
                return ResourceManager.GetString("SandboxMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Accounts.
        /// </summary>
        internal static string ShowAccounts {
            get {
                return ResourceManager.GetString("ShowAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Credentials.
        /// </summary>
        internal static string ShowCredentials {
            get {
                return ResourceManager.GetString("ShowCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot.
        /// </summary>
        internal static string Spot {
            get {
                return ResourceManager.GetString("Spot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot Order.
        /// </summary>
        internal static string SpotOrder {
            get {
                return ResourceManager.GetString("SpotOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Loss.
        /// </summary>
        internal static string StopLoss {
            get {
                return ResourceManager.GetString("StopLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Mode.
        /// </summary>
        internal static string StopMode {
            get {
                return ResourceManager.GetString("StopMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Order.
        /// </summary>
        internal static string StopOrder {
            get {
                return ResourceManager.GetString("StopOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        internal static string Symbols {
            get {
                return ResourceManager.GetString("Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Profit.
        /// </summary>
        internal static string TakeProfit {
            get {
                return ResourceManager.GetString("TakeProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Symbol.
        /// </summary>
        internal static string TradingSymbol {
            get {
                return ResourceManager.GetString("TradingSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Symbols.
        /// </summary>
        internal static string TradingSymbols {
            get {
                return ResourceManager.GetString("TradingSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
    }
}
