//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kucoin.NET.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kucoin.NET.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Account.
        /// </summary>
        public static string Account_Type_ {
            get {
                return ResourceManager.GetString("Account.Type.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Futures Account.
        /// </summary>
        public static string Account_Type_futures {
            get {
                return ResourceManager.GetString("Account.Type.futures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Account.
        /// </summary>
        public static string Account_Type_main {
            get {
                return ResourceManager.GetString("Account.Type.main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin Account.
        /// </summary>
        public static string Account_Type_margin {
            get {
                return ResourceManager.GetString("Account.Type.margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool-X Account.
        /// </summary>
        public static string Account_Type_pool {
            get {
                return ResourceManager.GetString("Account.Type.pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Account.
        /// </summary>
        public static string Account_Type_trade {
            get {
                return ResourceManager.GetString("Account.Type.trade", resourceCulture);
            }
        }
    }
}
