//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuCoin.NET.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KuCoin.NET.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Account.
        /// </summary>
        public static string Account_Type_ {
            get {
                return ResourceManager.GetString("Account.Type.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Futures Account.
        /// </summary>
        public static string Account_Type_futures {
            get {
                return ResourceManager.GetString("Account.Type.futures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Account.
        /// </summary>
        public static string Account_Type_main {
            get {
                return ResourceManager.GetString("Account.Type.main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin Account.
        /// </summary>
        public static string Account_Type_margin {
            get {
                return ResourceManager.GetString("Account.Type.margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool-X Account.
        /// </summary>
        public static string Account_Type_pool {
            get {
                return ResourceManager.GetString("Account.Type.pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Account.
        /// </summary>
        public static string Account_Type_trade {
            get {
                return ResourceManager.GetString("Account.Type.trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Confirmations.
        /// </summary>
        public static string Currency_Confirms {
            get {
                return ResourceManager.GetString("Currency.Confirms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent Currency Code.
        /// </summary>
        public static string Currency_Currency {
            get {
                return ResourceManager.GetString("Currency.Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Currency Name.
        /// </summary>
        public static string Currency_FullName {
            get {
                return ResourceManager.GetString("Currency.FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports Debit.
        /// </summary>
        public static string Currency_IsDebitEnabled {
            get {
                return ResourceManager.GetString("Currency.IsDebitEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports Deposit.
        /// </summary>
        public static string Currency_IsDepositEnabled {
            get {
                return ResourceManager.GetString("Currency.IsDepositEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports Margin Trading.
        /// </summary>
        public static string Currency_IsMarginEnabled {
            get {
                return ResourceManager.GetString("Currency.IsMarginEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports Withdrawal.
        /// </summary>
        public static string Currency_IsWithdrawEnabled {
            get {
                return ResourceManager.GetString("Currency.IsWithdrawEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Name.
        /// </summary>
        public static string Currency_Name {
            get {
                return ResourceManager.GetString("Currency.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Precision.
        /// </summary>
        public static string Currency_Precision {
            get {
                return ResourceManager.GetString("Currency.Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Withdrawal Fee.
        /// </summary>
        public static string Currency_withdrawalMinFee {
            get {
                return ResourceManager.GetString("Currency.withdrawalMinFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Withdrawal Amaount.
        /// </summary>
        public static string Currency_WithdrawalMinSize {
            get {
                return ResourceManager.GetString("Currency.WithdrawalMinSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency.
        /// </summary>
        public static string TradingSymbol_BaseCurrency {
            get {
                return ResourceManager.GetString("TradingSymbol.BaseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency Increment.
        /// </summary>
        public static string TradingSymbol_BaseIncrement {
            get {
                return ResourceManager.GetString("TradingSymbol.BaseIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency Maximum Size.
        /// </summary>
        public static string TradingSymbol_BaseMaxSize {
            get {
                return ResourceManager.GetString("TradingSymbol.BaseMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency Minimum Size.
        /// </summary>
        public static string TradingSymbol_BaseMinSize {
            get {
                return ResourceManager.GetString("TradingSymbol.BaseMinSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports Trading.
        /// </summary>
        public static string TradingSymbol_EnableTrading {
            get {
                return ResourceManager.GetString("TradingSymbol.EnableTrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Currency.
        /// </summary>
        public static string TradingSymbol_FeeCurrency {
            get {
                return ResourceManager.GetString("TradingSymbol.FeeCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports Margin Trading.
        /// </summary>
        public static string TradingSymbol_IsMarginEnabled {
            get {
                return ResourceManager.GetString("TradingSymbol.IsMarginEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Symbol Name.
        /// </summary>
        public static string TradingSymbol_Name {
            get {
                return ResourceManager.GetString("TradingSymbol.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Increment.
        /// </summary>
        public static string TradingSymbol_PriceIncrement {
            get {
                return ResourceManager.GetString("TradingSymbol.PriceIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Limit Rate.
        /// </summary>
        public static string TradingSymbol_PriceLimitRate {
            get {
                return ResourceManager.GetString("TradingSymbol.PriceLimitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Currency.
        /// </summary>
        public static string TradingSymbol_QuoteCurrency {
            get {
                return ResourceManager.GetString("TradingSymbol.QuoteCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Currency Increment.
        /// </summary>
        public static string TradingSymbol_QuoteIncrement {
            get {
                return ResourceManager.GetString("TradingSymbol.QuoteIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Currency Maximum Size.
        /// </summary>
        public static string TradingSymbol_QuoteMaxSize {
            get {
                return ResourceManager.GetString("TradingSymbol.QuoteMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Currency Minimum Size.
        /// </summary>
        public static string TradingSymbol_QuoteMinSize {
            get {
                return ResourceManager.GetString("TradingSymbol.QuoteMinSize", resourceCulture);
            }
        }
    }
}
